from piper import PiperVoice # needed for text to speech
import pygame # needed to play the wav files generated by piper
import wave # needed to read and write wav files

import sys # needed for printing errors to stderr
import time # needed for sleep

tts_voice = PiperVoice.load("en_US-amy-medium.onnx") # load the piper voice for text to speech
output_file = "output.wav" # the file where the generated speech will be saved

# initialize pygame mixer to play the generated wav file
pygame.mixer.init()

def say(text):
    """
    sample method to turn text into speech

    Args:
        text (string): The text to be converted to speech
    """

    with wave.open(output_file, 'wb') as f:
        # set the parameters for the wav file

        # generate the speech and write it to the wav file
        tts_voice.synthesize_wav(text, f)

    # play the generated wav file
    pygame.mixer.Sound(output_file).play()

    while pygame.mixer.get_busy(): # wait for the audio to finish playing
        time.sleep(0.1)

if __name__ == "__main__":
    print("Text to Speech Test")

    while True:

        text = input("Enter text to convert to speech: ")
        if text.lower() == "exit":
            print("Exiting...")
            break
        
        say(text)